/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as ModelsIndexRouteImport } from './routes/models.index'
import { Route as ModelsSlugRouteImport } from './routes/models.$slug'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardBillingRouteImport } from './routes/_authenticated/dashboard.billing'
import { Route as AuthenticatedDashboardBrokersRouteImport } from './routes/_authenticated/dashboard.brokers'
import { Route as AuthenticatedDashboardDataSourcesRouteImport } from './routes/_authenticated/dashboard.data-sources'
import { Route as AuthenticatedDashboardMarketplaceRouteImport } from './routes/_authenticated/dashboard.marketplace'
import { Route as AuthenticatedDashboardPaperTradingRouteImport } from './routes/_authenticated/dashboard.paper-trading'
import { Route as AuthenticatedDashboardRiskRouteImport } from './routes/_authenticated/dashboard.risk'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard.settings'
import { Route as ApiPublicSyncRouteImport } from './routes/api/public/sync'
import { Route as AuthenticatedDashboardModelsIndexRouteImport } from './routes/_authenticated/dashboard.models.index'
import { Route as AuthenticatedDashboardStrategiesIndexRouteImport } from './routes/_authenticated/dashboard.strategies.index'
import { Route as AuthenticatedDashboardStrategiesBacktestRouteImport } from './routes/_authenticated/dashboard.strategies.backtest'
import { Route as AuthenticatedDashboardStrategiesBuilderRouteImport } from './routes/_authenticated/dashboard.strategies.builder'
import { Route as AuthenticatedDashboardStrategiesTemplatesRouteImport } from './routes/_authenticated/dashboard.strategies.templates'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const ModelsIndexRoute = ModelsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModelsRoute,
} as any)
const ModelsSlugRoute = ModelsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ModelsRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBillingRoute =
  AuthenticatedDashboardBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBrokersRoute =
  AuthenticatedDashboardBrokersRouteImport.update({
    id: '/brokers',
    path: '/brokers',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDataSourcesRoute =
  AuthenticatedDashboardDataSourcesRouteImport.update({
    id: '/data-sources',
    path: '/data-sources',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMarketplaceRoute =
  AuthenticatedDashboardMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPaperTradingRoute =
  AuthenticatedDashboardPaperTradingRouteImport.update({
    id: '/paper-trading',
    path: '/paper-trading',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardRiskRoute =
  AuthenticatedDashboardRiskRouteImport.update({
    id: '/risk',
    path: '/risk',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiPublicSyncRoute = ApiPublicSyncRouteImport.update({
  id: '/api/public/sync',
  path: '/api/public/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardModelsIndexRoute =
  AuthenticatedDashboardModelsIndexRouteImport.update({
    id: '/models/',
    path: '/models/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardStrategiesIndexRoute =
  AuthenticatedDashboardStrategiesIndexRouteImport.update({
    id: '/strategies/',
    path: '/strategies/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardStrategiesBacktestRoute =
  AuthenticatedDashboardStrategiesBacktestRouteImport.update({
    id: '/strategies/backtest',
    path: '/strategies/backtest',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardStrategiesBuilderRoute =
  AuthenticatedDashboardStrategiesBuilderRouteImport.update({
    id: '/strategies/builder',
    path: '/strategies/builder',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardStrategiesTemplatesRoute =
  AuthenticatedDashboardStrategiesTemplatesRouteImport.update({
    id: '/strategies/templates',
    path: '/strategies/templates',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/models': typeof ModelsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/models/$slug': typeof ModelsSlugRoute
  '/auth/': typeof AuthIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/dashboard/brokers': typeof AuthenticatedDashboardBrokersRoute
  '/dashboard/data-sources': typeof AuthenticatedDashboardDataSourcesRoute
  '/dashboard/marketplace': typeof AuthenticatedDashboardMarketplaceRoute
  '/dashboard/paper-trading': typeof AuthenticatedDashboardPaperTradingRoute
  '/dashboard/risk': typeof AuthenticatedDashboardRiskRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/api/public/sync': typeof ApiPublicSyncRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/strategies/backtest': typeof AuthenticatedDashboardStrategiesBacktestRoute
  '/dashboard/strategies/builder': typeof AuthenticatedDashboardStrategiesBuilderRoute
  '/dashboard/strategies/templates': typeof AuthenticatedDashboardStrategiesTemplatesRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/dashboard/models/': typeof AuthenticatedDashboardModelsIndexRoute
  '/dashboard/strategies/': typeof AuthenticatedDashboardStrategiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/models/$slug': typeof ModelsSlugRoute
  '/auth': typeof AuthIndexRoute
  '/models': typeof ModelsIndexRoute
  '/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/dashboard/brokers': typeof AuthenticatedDashboardBrokersRoute
  '/dashboard/data-sources': typeof AuthenticatedDashboardDataSourcesRoute
  '/dashboard/marketplace': typeof AuthenticatedDashboardMarketplaceRoute
  '/dashboard/paper-trading': typeof AuthenticatedDashboardPaperTradingRoute
  '/dashboard/risk': typeof AuthenticatedDashboardRiskRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/api/public/sync': typeof ApiPublicSyncRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/strategies/backtest': typeof AuthenticatedDashboardStrategiesBacktestRoute
  '/dashboard/strategies/builder': typeof AuthenticatedDashboardStrategiesBuilderRoute
  '/dashboard/strategies/templates': typeof AuthenticatedDashboardStrategiesTemplatesRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/dashboard/models': typeof AuthenticatedDashboardModelsIndexRoute
  '/dashboard/strategies': typeof AuthenticatedDashboardStrategiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/models': typeof ModelsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/models/$slug': typeof ModelsSlugRoute
  '/auth/': typeof AuthIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/_authenticated/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/_authenticated/dashboard/brokers': typeof AuthenticatedDashboardBrokersRoute
  '/_authenticated/dashboard/data-sources': typeof AuthenticatedDashboardDataSourcesRoute
  '/_authenticated/dashboard/marketplace': typeof AuthenticatedDashboardMarketplaceRoute
  '/_authenticated/dashboard/paper-trading': typeof AuthenticatedDashboardPaperTradingRoute
  '/_authenticated/dashboard/risk': typeof AuthenticatedDashboardRiskRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/api/public/sync': typeof ApiPublicSyncRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/strategies/backtest': typeof AuthenticatedDashboardStrategiesBacktestRoute
  '/_authenticated/dashboard/strategies/builder': typeof AuthenticatedDashboardStrategiesBuilderRoute
  '/_authenticated/dashboard/strategies/templates': typeof AuthenticatedDashboardStrategiesTemplatesRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/_authenticated/dashboard/models/': typeof AuthenticatedDashboardModelsIndexRoute
  '/_authenticated/dashboard/strategies/': typeof AuthenticatedDashboardStrategiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/models'
    | '/dashboard'
    | '/onboarding'
    | '/auth/login'
    | '/auth/register'
    | '/models/$slug'
    | '/auth/'
    | '/models/'
    | '/dashboard/billing'
    | '/dashboard/brokers'
    | '/dashboard/data-sources'
    | '/dashboard/marketplace'
    | '/dashboard/paper-trading'
    | '/dashboard/risk'
    | '/dashboard/settings'
    | '/api/public/sync'
    | '/dashboard/'
    | '/dashboard/strategies/backtest'
    | '/dashboard/strategies/builder'
    | '/dashboard/strategies/templates'
    | '/api/public/payments/webhook'
    | '/dashboard/models/'
    | '/dashboard/strategies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/auth/login'
    | '/auth/register'
    | '/models/$slug'
    | '/auth'
    | '/models'
    | '/dashboard/billing'
    | '/dashboard/brokers'
    | '/dashboard/data-sources'
    | '/dashboard/marketplace'
    | '/dashboard/paper-trading'
    | '/dashboard/risk'
    | '/dashboard/settings'
    | '/api/public/sync'
    | '/dashboard'
    | '/dashboard/strategies/backtest'
    | '/dashboard/strategies/builder'
    | '/dashboard/strategies/templates'
    | '/api/public/payments/webhook'
    | '/dashboard/models'
    | '/dashboard/strategies'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/models'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/auth/login'
    | '/auth/register'
    | '/models/$slug'
    | '/auth/'
    | '/models/'
    | '/_authenticated/dashboard/billing'
    | '/_authenticated/dashboard/brokers'
    | '/_authenticated/dashboard/data-sources'
    | '/_authenticated/dashboard/marketplace'
    | '/_authenticated/dashboard/paper-trading'
    | '/_authenticated/dashboard/risk'
    | '/_authenticated/dashboard/settings'
    | '/api/public/sync'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/strategies/backtest'
    | '/_authenticated/dashboard/strategies/builder'
    | '/_authenticated/dashboard/strategies/templates'
    | '/api/public/payments/webhook'
    | '/_authenticated/dashboard/models/'
    | '/_authenticated/dashboard/strategies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ModelsRoute: typeof ModelsRouteWithChildren
  ApiPublicSyncRoute: typeof ApiPublicSyncRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/models/': {
      id: '/models/'
      path: '/'
      fullPath: '/models/'
      preLoaderRoute: typeof ModelsIndexRouteImport
      parentRoute: typeof ModelsRoute
    }
    '/models/$slug': {
      id: '/models/$slug'
      path: '/$slug'
      fullPath: '/models/$slug'
      preLoaderRoute: typeof ModelsSlugRouteImport
      parentRoute: typeof ModelsRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/billing': {
      id: '/_authenticated/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof AuthenticatedDashboardBillingRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/brokers': {
      id: '/_authenticated/dashboard/brokers'
      path: '/brokers'
      fullPath: '/dashboard/brokers'
      preLoaderRoute: typeof AuthenticatedDashboardBrokersRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/data-sources': {
      id: '/_authenticated/dashboard/data-sources'
      path: '/data-sources'
      fullPath: '/dashboard/data-sources'
      preLoaderRoute: typeof AuthenticatedDashboardDataSourcesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/marketplace': {
      id: '/_authenticated/dashboard/marketplace'
      path: '/marketplace'
      fullPath: '/dashboard/marketplace'
      preLoaderRoute: typeof AuthenticatedDashboardMarketplaceRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/paper-trading': {
      id: '/_authenticated/dashboard/paper-trading'
      path: '/paper-trading'
      fullPath: '/dashboard/paper-trading'
      preLoaderRoute: typeof AuthenticatedDashboardPaperTradingRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/risk': {
      id: '/_authenticated/dashboard/risk'
      path: '/risk'
      fullPath: '/dashboard/risk'
      preLoaderRoute: typeof AuthenticatedDashboardRiskRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/public/sync': {
      id: '/api/public/sync'
      path: '/api/public/sync'
      fullPath: '/api/public/sync'
      preLoaderRoute: typeof ApiPublicSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/models/': {
      id: '/_authenticated/dashboard/models/'
      path: '/models'
      fullPath: '/dashboard/models/'
      preLoaderRoute: typeof AuthenticatedDashboardModelsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/strategies/': {
      id: '/_authenticated/dashboard/strategies/'
      path: '/strategies'
      fullPath: '/dashboard/strategies/'
      preLoaderRoute: typeof AuthenticatedDashboardStrategiesIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/strategies/backtest': {
      id: '/_authenticated/dashboard/strategies/backtest'
      path: '/strategies/backtest'
      fullPath: '/dashboard/strategies/backtest'
      preLoaderRoute: typeof AuthenticatedDashboardStrategiesBacktestRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/strategies/builder': {
      id: '/_authenticated/dashboard/strategies/builder'
      path: '/strategies/builder'
      fullPath: '/dashboard/strategies/builder'
      preLoaderRoute: typeof AuthenticatedDashboardStrategiesBuilderRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/strategies/templates': {
      id: '/_authenticated/dashboard/strategies/templates'
      path: '/strategies/templates'
      fullPath: '/dashboard/strategies/templates'
      preLoaderRoute: typeof AuthenticatedDashboardStrategiesTemplatesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardBillingRoute: typeof AuthenticatedDashboardBillingRoute
  AuthenticatedDashboardBrokersRoute: typeof AuthenticatedDashboardBrokersRoute
  AuthenticatedDashboardDataSourcesRoute: typeof AuthenticatedDashboardDataSourcesRoute
  AuthenticatedDashboardMarketplaceRoute: typeof AuthenticatedDashboardMarketplaceRoute
  AuthenticatedDashboardPaperTradingRoute: typeof AuthenticatedDashboardPaperTradingRoute
  AuthenticatedDashboardRiskRoute: typeof AuthenticatedDashboardRiskRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardStrategiesBacktestRoute: typeof AuthenticatedDashboardStrategiesBacktestRoute
  AuthenticatedDashboardStrategiesBuilderRoute: typeof AuthenticatedDashboardStrategiesBuilderRoute
  AuthenticatedDashboardStrategiesTemplatesRoute: typeof AuthenticatedDashboardStrategiesTemplatesRoute
  AuthenticatedDashboardModelsIndexRoute: typeof AuthenticatedDashboardModelsIndexRoute
  AuthenticatedDashboardStrategiesIndexRoute: typeof AuthenticatedDashboardStrategiesIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardBillingRoute: AuthenticatedDashboardBillingRoute,
    AuthenticatedDashboardBrokersRoute: AuthenticatedDashboardBrokersRoute,
    AuthenticatedDashboardDataSourcesRoute:
      AuthenticatedDashboardDataSourcesRoute,
    AuthenticatedDashboardMarketplaceRoute:
      AuthenticatedDashboardMarketplaceRoute,
    AuthenticatedDashboardPaperTradingRoute:
      AuthenticatedDashboardPaperTradingRoute,
    AuthenticatedDashboardRiskRoute: AuthenticatedDashboardRiskRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardStrategiesBacktestRoute:
      AuthenticatedDashboardStrategiesBacktestRoute,
    AuthenticatedDashboardStrategiesBuilderRoute:
      AuthenticatedDashboardStrategiesBuilderRoute,
    AuthenticatedDashboardStrategiesTemplatesRoute:
      AuthenticatedDashboardStrategiesTemplatesRoute,
    AuthenticatedDashboardModelsIndexRoute:
      AuthenticatedDashboardModelsIndexRoute,
    AuthenticatedDashboardStrategiesIndexRoute:
      AuthenticatedDashboardStrategiesIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ModelsRouteChildren {
  ModelsSlugRoute: typeof ModelsSlugRoute
  ModelsIndexRoute: typeof ModelsIndexRoute
}

const ModelsRouteChildren: ModelsRouteChildren = {
  ModelsSlugRoute: ModelsSlugRoute,
  ModelsIndexRoute: ModelsIndexRoute,
}

const ModelsRouteWithChildren =
  ModelsRoute._addFileChildren(ModelsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ModelsRoute: ModelsRouteWithChildren,
  ApiPublicSyncRoute: ApiPublicSyncRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
