
REVOKE ALL ON FUNCTION public.has_role(uuid, public.app_role) FROM public, anon;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated, service_role;
REVOKE ALL ON FUNCTION public.handle_new_user() FROM public, anon, authenticated;
REVOKE ALL ON FUNCTION public.touch_updated_at() FROM public, anon, authenticated;

INSERT INTO public.strategies (user_id, name, description, category, market_condition, risk_level, is_template, is_public, creator_name, graph, parameters) VALUES
(NULL,'Mean Reversion (RSI)','Buys when RSI drops into oversold territory and exits when momentum normalises. Works best in choppy, range-bound markets.','mean_reversion','sideways','Medium',true,true,'AlgoForge',
 '{"nodes":[{"id":"n1","type":"data","position":{"x":40,"y":80},"data":{"kind":"indicator","label":"RSI","params":{"period":14}}},{"id":"n2","type":"condition","position":{"x":320,"y":80},"data":{"kind":"less_than","label":"Less Than","params":{"value":30}}},{"id":"n3","type":"action","position":{"x":600,"y":40},"data":{"kind":"buy_market","label":"Buy Market","params":{"size":100}}},{"id":"n4","type":"condition","position":{"x":320,"y":220},"data":{"kind":"greater_than","label":"Greater Than","params":{"value":65}}},{"id":"n5","type":"action","position":{"x":600,"y":220},"data":{"kind":"sell_market","label":"Sell Market","params":{"size":100}}}],"edges":[{"id":"e1","source":"n1","target":"n2"},{"id":"e2","source":"n2","target":"n3"},{"id":"e3","source":"n1","target":"n4"},{"id":"e4","source":"n4","target":"n5"}]}'::jsonb,
 '{"rsi_period":14,"oversold":30,"overbought":65}'::jsonb),
(NULL,'Trend Following (Dual MA)','Classic golden-cross system: go long when the fast moving average crosses above the slow one, exit on the death cross.','trend_following','bull','Low',true,true,'AlgoForge',
 '{"nodes":[{"id":"n1","type":"data","position":{"x":40,"y":60},"data":{"kind":"indicator","label":"SMA","params":{"period":50}}},{"id":"n2","type":"data","position":{"x":40,"y":200},"data":{"kind":"indicator","label":"SMA","params":{"period":200}}},{"id":"n3","type":"condition","position":{"x":320,"y":130},"data":{"kind":"cross_above","label":"Cross Above","params":{}}},{"id":"n4","type":"action","position":{"x":600,"y":80},"data":{"kind":"buy_market","label":"Buy Market","params":{"size":100}}},{"id":"n5","type":"action","position":{"x":600,"y":220},"data":{"kind":"set_stop_loss","label":"Set Stop Loss","params":{"percent":5}}}],"edges":[{"id":"e1","source":"n1","target":"n3"},{"id":"e2","source":"n2","target":"n3"},{"id":"e3","source":"n3","target":"n4"},{"id":"e4","source":"n4","target":"n5"}]}'::jsonb,
 '{"fast":50,"slow":200,"stop_loss_pct":5}'::jsonb),
(NULL,'Breakout (Bollinger Squeeze)','Waits for volatility to compress, then rides the expansion when price breaks the upper band.','breakout','bull','High',true,true,'AlgoForge',
 '{"nodes":[{"id":"n1","type":"data","position":{"x":40,"y":100},"data":{"kind":"indicator","label":"Bollinger Bands","params":{"period":20,"stddev":2}}},{"id":"n2","type":"condition","position":{"x":320,"y":100},"data":{"kind":"cross_above","label":"Cross Above","params":{}}},{"id":"n3","type":"action","position":{"x":600,"y":60},"data":{"kind":"buy_market","label":"Buy Market","params":{"size":100}}},{"id":"n4","type":"risk","position":{"x":600,"y":200},"data":{"kind":"max_position_size","label":"Max Position Size","params":{"percent":20}}}],"edges":[{"id":"e1","source":"n1","target":"n2"},{"id":"e2","source":"n2","target":"n3"},{"id":"e3","source":"n3","target":"n4"}]}'::jsonb,
 '{"period":20,"stddev":2}'::jsonb),
(NULL,'Grid Trading','Places laddered buy and sell orders around a reference price to harvest oscillation in sideways markets.','grid','sideways','Medium',true,true,'AlgoForge',
 '{"nodes":[{"id":"n1","type":"data","position":{"x":40,"y":100},"data":{"kind":"price","label":"Price (Close)","params":{}}},{"id":"n2","type":"condition","position":{"x":320,"y":40},"data":{"kind":"less_than","label":"Less Than","params":{"value":-2}}},{"id":"n3","type":"action","position":{"x":600,"y":40},"data":{"kind":"buy_limit","label":"Buy Limit","params":{"size":25}}},{"id":"n4","type":"condition","position":{"x":320,"y":200},"data":{"kind":"greater_than","label":"Greater Than","params":{"value":2}}},{"id":"n5","type":"action","position":{"x":600,"y":200},"data":{"kind":"sell_limit","label":"Sell Limit","params":{"size":25}}}],"edges":[{"id":"e1","source":"n1","target":"n2"},{"id":"e2","source":"n2","target":"n3"},{"id":"e3","source":"n1","target":"n4"},{"id":"e4","source":"n4","target":"n5"}]}'::jsonb,
 '{"grid_step_pct":2,"levels":4}'::jsonb),
(NULL,'Pairs Trading (Correlation)','Trades the spread between two correlated names, buying the laggard and shorting the leader when they diverge.','pairs','sideways','High',true,true,'AlgoForge',
 '{"nodes":[{"id":"n1","type":"data","position":{"x":40,"y":60},"data":{"kind":"price","label":"Price (Close)","params":{}}},{"id":"n2","type":"data","position":{"x":40,"y":200},"data":{"kind":"indicator","label":"EMA","params":{"period":20}}},{"id":"n3","type":"condition","position":{"x":320,"y":130},"data":{"kind":"cross_below","label":"Cross Below","params":{}}},{"id":"n4","type":"action","position":{"x":600,"y":130},"data":{"kind":"buy_market","label":"Buy Market","params":{"size":50}}},{"id":"n5","type":"risk","position":{"x":600,"y":260},"data":{"kind":"max_daily_loss","label":"Max Daily Loss","params":{"percent":3}}}],"edges":[{"id":"e1","source":"n1","target":"n3"},{"id":"e2","source":"n2","target":"n3"},{"id":"e3","source":"n3","target":"n4"},{"id":"e4","source":"n4","target":"n5"}]}'::jsonb,
 '{"lookback":20,"zscore_entry":2}'::jsonb);
